import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="m-3 p-4 flex items-center space-x-4 border border-white rounded-lg">
          <Link href={"/"}>Home</Link>
          <Link href={"/categories"}>Categories</Link>
          <Link href={"/products"}>Products</Link>
          <Link href={"/account"}>Account</Link>
          <Link href={"/payment-history"}>Payment History</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
