import classnames from "classnames";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classnames(inter.className, "grid grid-cols-6")}>
        <nav className="col-span-1 bg-gray-900 h-screen border-r border-r-gray-800 flex flex-col">
          <h1 className="text-2xl border-b p-4 border-b-gray-800">
            Your Dashboard
          </h1>
          <ul className="p-4 space-y-3">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/dashboard"}>Dashboard</Link>
            </li>
          </ul>
        </nav>
        <main className="col-span-5 p-4">{children}</main>
      </body>
    </html>
  );
}
