import classNames from "classnames"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          "flex flex-col items-center justify-center min-h-screen space-y-6"
        )}
      >
        <header>
          <h2 className="text-4xl">
            🏃‍♀️ Data Fetching, Caching and Revalidating
          </h2>
        </header>
        <main className="w-full md:w-1/2">{children}</main>
      </body>
    </html>
  )
}
